### PR TITLE
Add osx test on Travis CI

### PR DESCRIPTION
**Pull request by equal-l2**
At this moment we run the test for osx but ignore the result.

### CODE REVIEW

**Comment by equal-l2** [comment]
OSX test seems not to be running.
Please wait for merging.

**Comment by maekawatoshiki** [comment]
To support osx, preprocessor must be upgraded.

**Comment by equal-l2** [comment]
Yes, the preprocessor has a problem with `/usr/include/AvailabilityInternal.h`.

**Comment by maekawatoshiki** [comment]
Can you fix it? Now I can't use osx..

**Comment by equal-l2** [comment]
Maybe I can, but won't be soon.

**Comment by maekawatoshiki** [comment]
OK. If I can use osx someday, I'll do.

**Comment by equal-l2** [comment]
A problem is a macro below in `AvailabilityInternal.h`.
```c
#define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
```
QCC cannot process this macro and claims `expected ','`.

**Comment by maekawatoshiki** [comment]
That's right. Cause of this problem is that preprocessor is not completely correct.

**Comment by equal-l2** [comment]
Is variadic macro not implemented yet?

**Comment by maekawatoshiki** [comment]
Yes. Not implemented

**Comment by equal-l2** [comment]
Then something like "Implementing variadic macro" should be in the Project.

**Comment by equal-l2** [comment]
`test/globalv.c` doesn't build because type `i8*` is passed to `llvm::ConstantAggregateZero::get`.
(On https://github.com/maekawatoshiki/qcc/blob/6cbb0bee9ccd0e5fe8fdaae21b0bc74d46125c3f/src/codegen.cpp#L250)

Since asserts in LLVM are disabled on ubuntu, it works well on ubuntu.
If asserts are enabled, compilation will stop with this assert message.
```
Assertion failed: ((Ty->isStructTy() || Ty->isArrayTy() || Ty->isVectorTy()) && "Cannot create an aggregate zero of non-aggregate type!"), function get, file /private/tmp/llvm@3.8-20170130-27399-1g3iurp/llvm-3.8.1.src/lib/IR/Constants.cpp, line 1314.
```

I don't know LLVM API at all, so I can't fix this problem.

**Comment by maekawatoshiki** [comment]
OK, I'll fix soon

**Comment by maekawatoshiki** [comment]
BTW could you tell me enable assert ?
I don't know...

**Comment by equal-l2** [comment]
> could you tell me enable assert ?

You can't do that with llvm provided by ubuntu, since asserts are disabled in build time.
(If you see [the build log](https://launchpadlibrarian.net/284183092/buildlog_ubuntu-yakkety-amd64.llvm-toolchain-3.8_1%3A3.8.1-12ubuntu1_BUILDING.txt.gz), you will find `--disable-assertion`)
You need to build llvm from source or use the other system (or maybe the other distro) with assert-enabled LLVM package.

**Comment by maekawatoshiki** [comment]
I see. I had tried to build llvm from source code. But then, the build failed because memory was not enough to build... 
Probably I'll give up.

**Comment by equal-l2** [comment]
As a personal opinion, I recommend you FreeBSD.
FreeBSD can run on VirtualBox, can be installed in a short time, and FreeBSD's binary package `llvm38` is assert-enabled.

**Comment by maekawatoshiki** [comment]
Oh that's great. I'll try.

**Comment by maekawatoshiki** [comment]
Thanks a lot!!

**Comment by equal-l2** [comment]
This PR has too much commits to simply merge.
Probably I should separate this to parts, or simply squash.

**Comment by maekawatoshiki** [comment]
Don't mind. Can I merge?

**Comment by equal-l2** [comment]
I've squashed all commits into one.
You can merge now.

**Comment by maekawatoshiki** [comment]
merged

**Pull request merged**
